import About from "@/components/About";
import BackToTop from "@/components/BackToTop";
import Banner from "@/components/Banner";
import Contact from "@/components/Contact";
import Education from "@/components/Education";
import Footer from "@/components/Footer";
import LeftSide from "@/components/LeftSide";
import Navbar from "@/components/Navbar";
import Projects from "@/components/Projects";
// import RightSide from "@/components/RightSide";
import Head from "next/head";
import { motion } from "framer-motion";
// import Archive from "@/components/Archive";

const sectionVariants = {
  hidden: { opacity: 0, y: 40 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.5, ease: "easeOut" },
  },
};

const viewportOptions = { once: true, amount: 0.15 };

export default function Home() {
  return (
    <>
      <Head>
        <title>Rithika</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
      </Head>
      <main className='w-full h-screen font-bodyFont bg-bodyColor text-textLight  overflow-x-hidden overflow-y-scroll scrollbar scrollbar-track-textDark/20 scrollbar-thumb-textDark/60'>
        <Navbar />
        <div className='w-full h-[88vh] xl:flex items-center gap-20 justify-between'>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
            className='hidden xl:inline-flex w-32 h-full fixed left-0 bottom-0'
          >
            <LeftSide />
          </motion.div>
          <div className='h-[88vh] mx-auto p-4'>
            <Banner />
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={viewportOptions}
              variants={sectionVariants}
            >
              <About />
            </motion.div>
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={viewportOptions}
              variants={sectionVariants}
            >
              <Education />
            </motion.div>
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={viewportOptions}
              variants={sectionVariants}
            >
              <Projects />
            </motion.div>
            {/* <Archive /> */}
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={viewportOptions}
              variants={sectionVariants}
            >
              <Contact />
            </motion.div>
            <motion.div
              initial="hidden"
              whileInView="visible"
              viewport={viewportOptions}
              variants={sectionVariants}
            >
              <Footer />
            </motion.div>
          </div>
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.5 }}
            className='hidden xl:inline-flex w-32 h-full fixed right-0 bottom-0'
          >
            {/* <RightSide /> */}
          </motion.div>
          <BackToTop />
        </div>
      </main>
    </>
  );
}
